
export default [
    {
        id: '1',
        img: 'https://i.postimg.cc/ZWCgq9zZ/g92-2-500x500-1.png',
        heading: "Redgear Pro Wireless Gamepad with 2.4GHz Wireless Technology, Integrated Dual Intensity Motor, Illuminated Keys for PC(Compatible with Windows 7/8/8.1/10 only)",
        price: "$120",
        del_price: "$160",
        blueIcon: [1, 2, 3, 4, 5],
    },
    {
        id: '2',
        img: 'https://i.postimg.cc/BLkbdP36/Frame-612.png',
        heading: "Zebronics Zeb-Transformer Gaming Keyboard and Mouse Combo (USB, Braided Cable)",
        price: "$960",
        del_price: "$1160",
        blueIcon: [1, 2, 3, 4],
        nullIcon: [1],
    },
    {
        id: '3',
        img: 'https://i.postimg.cc/RJ1mXWV2/Frame-613.png',
        heading: "Samsung 24-Inch(59.8cm) FHD, 75 Hz, 1800R Curved 1,920 X 1,080 LED Monitor, VA Panel, Slim Design, AMD Freesync, Game Mode, Flicker Free, HDMI, Audio Port (LS24C360EAWXXL, Black)",
        price: "$370",
        del_price: "$400",
        blueIcon: [1, 2, 3, 4, 5],
    },
    {
        id: '4',
        img: 'https://i.postimg.cc/hJRH3SNB/Frame-614.png',
        heading: "Nilkamal Fyrebird Ergonomic Gaming Chair with Lumbar Pillow, 3D Adjustable Armrest, Adjustable Neck, Gas Lift Mechanism, & 100mm Tilt (Canophy)",
        price: "$375",
        del_price: "$400",
        blueIcon: [1, 2, 3, 4],
        halfIcon: [1],
    },
    {
        id: '5',
        img: 'https://i.postimg.cc/Mf1B5mBx/ideapad-gaming.png',
        heading: "HP Laptop 15s, 12th Gen Intel Core i3, 15.6-inch (39.6 cm), 8GB DDR4, 512GB SSD, Thin & Light, Dual Speakers (Win 11, MSO 2021, Silver, 1.69 kg), fq5007TU / FQ5327TU",
        price: "$500",
        del_price: "$800",
        blueIcon: [1, 2, 3, 4],
        halfIcon: [1],
    },
    {
        id: '6',
        img: 'https://i.postimg.cc/B8dtz14v/pexels-joey-nguy-n-2113994-removebg-preview-1.png',
        heading: "SKMEI Men's Watch New Wheels Rolling Creative Fashion Che Youhui League Fans Butterfly Double Snap Gift Wristwatch - 1990",
        price: "$260",
        del_price: "$700",
        blueIcon: [1, 2, 3, 4],
        nullIcon: [1],
    },
    {
        id: '7',
        img: 'https://i.postimg.cc/1gcz3RFm/pexels-dzenina-lukac-815494-removebg-preview.png',
        heading: "Sony WH-CH720N, Wireless Over-Ear Active Noise Cancellation Headphones with Mic, up to 35 Hours Playtime, Multi-Point Connection, App Support, AUX & Voice Assistant Support for Mobile Phones (Black)",
        price: "$700",
        del_price: "$1299",
        blueIcon: [1, 2, 3, 4, 5],
    },
    {
        id: '8',
        img: 'https://i.postimg.cc/nj2YBtyZ/pexels-cottonbro-studio-4009591-removebg-preview.png',
        heading: "VR Headset Compatible with iPhone & Android | Virtual Reality Goggles for 4.7”-6.5” Cell Phone - Best Set Glasses | Gift for Kids and Adults for 3D Gaming and VR Videos",
        price: "$655",
        del_price: "$999",
        blueIcon: [1, 2, 3, 4, 5],
    },
    {
        id: '9',
        img: 'https://i.postimg.cc/8jQPMrbp/Shirt-removebg-preview.png',
        heading: "IndoPrimo Men's Regular Fit Checks Cotton Casual Shirt for Men Full Sleeves - Suzuki",
        price: "$260",
        del_price: "$400",
        blueIcon: [1, 2, 3, 4, 5],
    },
    {
        id: '10',
        img: 'https://i.postimg.cc/tnzfsf5V/bag.png',
        heading: "FUR JADEN Anti Theft Number Lock Backpack Bag with 15.6 Inch Laptop Compartment, USB Charging Port & Organizer Pocket for Men Women Boys Girls",
        price: "$960",
        del_price: "$1160",
        blueIcon: [1, 2, 3, 4],
        nullIcon: [1],
    },
    {
        id: '11',
        img: 'https://i.postimg.cc/tnzfsf5V/bag.png',
        heading: "Lenovo (Renewed) Thinkcentre M700 Desktop Mini Pc (Intel Core I3 6Th Gen,8 Gb Ddr4 Ram,256 Gb Ssd,Wifi,Windows 11,Ms Office,Intel Hd Graphics,Usb,Dp)Black",
        price: "$160",
        del_price: "$200",
        blueIcon: [1, 2, 3, 4],
        halfIcon: [1],
    },
    {
        id: '12',
        img: 'https://i.postimg.cc/7fnGLVy8/table.png',
        heading: "PRIVILON GLOBAL Office Table For Home/Writing Desk For Office/Folding Table For School/Folding Study Table/Work From Home Multipurpose Table, (Black Cotted)",
        price: "$360",
        del_price: "$500",
        blueIcon: [1, 2, 3, 4, 5],
    },
    {
        id: '13',
        img: 'https://i.postimg.cc/TK2y5DRy/dogfood.png',
        heading: "Pedigree Pro Adult Small Breed, Dry Dog Food (9 Months Onwards), 3 Kg Pack, Chicken",
        price: "$100",
        del_price: '$250',
        blueIcon: [1, 2, 3],
        nullIcon: [1, 2],
        rating: "35",
    },
    {
        id: '14',
        img: 'https://i.postimg.cc/56byDCQP/camero.png',
        heading: "Canon EOS 3000D 18MP Digital SLR Camera (Black) with 18-55mm is II Lens, 16GB Card and Carry Case",
        price: "$360",
        del_price: '$550',
        blueIcon: [1, 2, 3, 4],
        nullIcon: [1],
        rating: "95",
    },
    {
        id: '15',
        img: 'https://i.postimg.cc/rRcy6Bsd/pexels-pixabay-4158-removebg-preview.png',
        heading: "Chuwi HeroBook Pro 14.1'' Intel Celeron N4020 Laptop with 8GB RAM, 256GB SSD, Windows 11, 1TB Expand, FHD IPS, Ultra Slim, USB3.0, Mini-HDMI, Webcam",
        price: "$700",
        del_price: '$950',
        blueIcon: [1, 2, 3, 4, 5],
        rating: "325",
    },
    {
        id: '16',
        img: 'https://i.postimg.cc/hXwdFGBf/product.png',
        heading: "mCaffeine Moment Gift Set For Women & Men With Natural Skin Care Products | Gift Kit For All Ages & Skin Types | Best Gift To Pamper Your Loved Ones | Premium & Luxurious Gift Box ",
        price: "$500",
        del_price: '$600',
        blueIcon: [1, 2, 3, 4],
        nullIcon: [1],
        rating: "145",
    },
    {
        id: '17',
        img: 'https://i.postimg.cc/xq0q4mz6/Electric-Toy-Car.png',
        heading: "TEC TAVAKKAL Remote Controlled Racing Car, Super Racing Sports High Speed Toy Vehicle, Motor RC Chargeable Cars for Kids Black",
        price: "$960",
        del_price: '$1250',
        blueIcon: [1, 2, 3, 4, 5],
        rating: "65",
    },
    {
        id: '18',
        img: 'https://i.postimg.cc/cKR4D14q/shoes.png',
        heading: "ASIAN Men's Tarzan-11 White Casual Sneaker High-Neck Shoes with Lightweight Extra Cushion Lace-Up Shoes for Men's & Boy's…",
        price: "$1160",
        del_price: '$2250',
        blueIcon: [1, 2, 3, 4, 5],
        rating: "35",
    },
    {
        id: '19',
        img: 'https://i.postimg.cc/jwf637nx/GP11-PRD3-1.png',
        heading: "Redgear Pro Wireless Gamepad with 2.4GHz Wireless Technology, Integrated Dual Intensity Motor, Illuminated Keys for PC(Compatible with Windows 7/8/8.1/10 only)",
        price: "$660",
        del_price: '$950',
        blueIcon: [1, 2, 3, 4],
        halfIcon: [1],
    },
    {
        id: '20',
        img: 'https://i.postimg.cc/cgfYBGP6/shirt.png',
        heading: "IndoPrimo Men's Cotton Casual Regular Fit Green Checks Shirt for Men Full Sleeves - Harley",
        price: "$660",
        del_price: '$900',
        blueIcon: [1, 2, 3, 4],
        halfIcon: [1],
    },
];
